[package]
name = "hb_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hb_macros = {path = "../hb_macros"}

[[example]]
name = "parsex"
test = true
edition = "2021"
crate-type = ["bin"]