[package]
name = "hb_error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hb_macros = {path = "../hb_macros"}

[dev-dependencies]
hb_parse = {path = "../hb_parse"}
